{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $content = $class_attribute.content}
<hr />
{* $class_attribute.content|attribute('show', 2) *}
<hr />
{* SQL Keys. *}
<div class="block">
    <label>{'SQL column(Seperated by Comma)'|i18n( 'design/standard/class/datatype' )}:</label>
    <input class="box" type="text" name="ContentClass_ezsqlquery_sql_headings_{$class_attribute.id}" value="{if is_set($content.Headings)}{$content.Headings|implode(',')}{/if}" />
</div>

{* SQL Keys. *}
<div class="block">
    <label>{'SQL Keys(Seperated by Comma)'|i18n( 'design/standard/class/datatype' )}:</label>
    <input class="box" type="text" name="ContentClass_ezsqlquery_sql_keys_{$class_attribute.id}" value="{if is_set($content.SQLKeys)}{$content.SQLKeys|implode(',')}{/if}" />
</div>

{* Select Query. *}
<div class="block">
    <label>{'Select Query'|i18n( 'design/standard/class/datatype' )}<span>*</span>:</label>
    <textarea class="box" name="ContentClass_ezsqlquery_select_query_{$class_attribute.id}">{if is_set($content.SelectQuery)}{$content.SelectQuery}{/if}</textarea>
</div>

{* Insert Query. *}
<div class="block">
    <label>{'Insert Query'|i18n( 'design/standard/class/datatype' )}:</label>
    <textarea class="box" name="ContentClass_ezsqlquery_insert_query_{$class_attribute.id}">{if is_set($content.InsertQuery)}{$content.InsertQuery}{/if}</textarea>
</div>

{* Update Query. *}
<div class="block">
    <label>{'Update Query'|i18n( 'design/standard/class/datatype' )}:</label>
    <textarea class="box" name="ContentClass_ezsqlquery_update_query_{$class_attribute.id}">{if is_set($content.UpdateQuery)}{$content.UpdateQuery}{/if}</textarea>
</div>

{* Update Query. *}
<div class="block">
    <label>{'Delete Query'|i18n( 'design/standard/class/datatype' )}:</label>
    <textarea class="box" name="ContentClass_ezsqlquery_delete_query_{$class_attribute.id}">{if is_set($content.DeleteQuery)}{$content.DeleteQuery}{/if}</textarea>
</div>

<div class="block">
    {if is_set($content.Views)}
        {foreach $content.Views as $key => $view}
            <div class="block">
                <div class="block">
                    <label >View Name</label>{$key}<input type="checkbox" name="ezsqlquery_deleteView{$class_attribute.id}[]" value="{$key}">
                </div>
                <div class="block">
                    <label for="ContentClass_ezsqlquery_views_query_{$class_attribute.id}[]">View Query</label>
                    <textarea class="box" name="ContentClass_ezsqlquery_views_query_{$class_attribute.id}[{$key}]">{$view}</textarea>
                </div>
            </div>
        {/foreach}
    {else}
        <p>No view created yet.</p>
    {/if}
    <div class="block">
        <h4>Add New View</h4>
        <div class="block">
            <label for="ezsqlquery_newViewName_{$class_attribute.id}">Name</label>
            <input class="box" type="text" name="ezsqlquery_newViewName_{$class_attribute.id}" value="" />
        </div>
        <div class="block">
            <label for="ezsqlquery_newViewQuery_{$class_attribute.id}">Query</label>
            <textarea class="box" name="ezsqlquery_newViewQuery_{$class_attribute.id}"></textarea>
        </div>

    </div>
    <div class="block">
        <input type="submit"  title="Add new view of Select Query." value="Add new view" name="CustomActionButton[{$class_attribute.id}_add_new_view]" class="button" />
        <input type="submit"  title="Delete all the selected views." value="Delete the selected view(s)" name="CustomActionButton[{$class_attribute.id}_remove_new_view]" class="button" />
    </div>
</div>

{undef $content}